### ISSUE TITLE
Add pay with pockets buttons

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/bitsplit#1]
To avoid copy/pasting, users should be able to click a pay-with-pockets button to load their fuel address.

![image](https://cloud.githubusercontent.com/assets/6858319/14766475/4ba9cb92-09c0-11e6-82a2-4e96a5960836.png)

**Comment by AdamBLevine** [comment]
Looks like there are a few extra places we could use pay-with-pockets. It should also be added anywhere a user is expected to pay an address

![image](https://cloud.githubusercontent.com/assets/6858319/14766498/76de827a-09c1-11e6-9cdf-e7fde2071462.png)

**Comment by cryptonaut420** [comment]
added to both fuel address and details page
