### ISSUE TITLE
Create distribution type/class for unique token payouts (see desc.)

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/bitsplit#13]

**Comment by cryptonaut420** [comment]
> Would like a feature to only pay a BTC address that has never been included in a distribution before. For example: We want to send a token called GOLDFOLDER to someone when they have reached 10,000,000 FAH points, or perhaps 100 days of folding. Once they receive the token once, we never want to send it again to them. This is just an idea we have, let us know how possible it is.

**Comment by AdamBLevine** [comment]
8 SP - Includes spec and implementation
