### ISSUE TITLE
Timestamp FLDC / token USD value on each distro creation (show values for each address + totals)

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/bitsplit#14]

**Comment by AdamBLevine** [comment]
MergedFolding should consult TokenMap for pricing.  Include that price in the historical information and use it to generate value/cost basis information for the whole distribution

5 SP

**Comment by cryptonaut420** [comment]
this is done. @deweller you will need to add `TOKENMAP_CONNECTION_URL` .env variable to the production server please when you get a chance
