### ISSUE TITLE
Amount to Distribute Total is Incorrect

### ISSUE THREAD

**Issue by deweller** [tokenly/bitsplit#30]
When selecting the top X folders, the amount calculated is incorrect.  In the example below, I entered 50 FLDC.  And the total is incorrectly reported as 500 FLDC.

![image](https://user-images.githubusercontent.com/51414/44682294-9d47f880-aa08-11e8-81fa-9512787dbaa5.png)

**Comment by rubenmeseguer7** [comment]
This should be fixed with the latest commit.

**Comment by deweller** [comment]
Looks good.  Thanks.
