### ISSUE TITLE
Distribution form incorrectly interpretting "1" quantity as 1 satoshi

### ISSUE THREAD

**Issue by AdamBLevine** [tokenly/bitsplit#4]
Looks like a decimal point got misplaced

![image](https://cloud.githubusercontent.com/assets/6858319/14767344/fff63e52-09d7-11e6-9788-1f4b4be11baa.png)

**Comment by cryptonaut420** [comment]
this is a blocktrail issue actually, they aren't accounting for divisible vs indivisible

**Comment by AdamBLevine** [comment]
Oh so the correct amount actually delivered?

Adam B. Levine
CEO, Tokenly <http://tokenly.com>

**Comment by cryptonaut420** [comment]
yes, e.g see here http://blockscan.com/address?q=1KFH1zV5asBR6J6T3qbtUwhoUnbN6KXYkf
